### ISSUE TITLE
where to find details about your project?

### ISSUE THREAD

**Issue by ghost** [foinio/foin#1]
hi i would like to know if you have a website, discord, twitter or any other socials that I can join to find more information about this project would be really nice, I have not been able to find anything so far!

**Comment by ardyfoin** [comment]
Hi. You can find for foin crypto is financial.org invest first, register and use this reference number 27026348.
And than you can find foin.
For guide you can open : 
1. foin.io
2. http://explorer.foin.io
3. Wallet.crypto-bridge.org
This is my whatsapp : +6282316173000

Thank you.

**Comment by foinio** [comment]
All relevant information can be found on our website, www.foin.io.
If you need any help with non-technical aspects of our projects, please use the contact email address listed on our website.
Thanks for your interest
